### ISSUE TITLE
Microsoft Defender Antivirus blocked AntiAlexa due to Backdoor:Win32/Bladabindi!ml 

### ISSUE THREAD

**Issue by zhaodelong** [LucaBarile/AntiAlexa#2]
Is this false alarm?

**Comment by LucaBarile** [comment]
Yes it is!
You can see and compile the [source code](https://github.com/LucaBarile/AntiAlexa/blob/main/AntiAlexa/AntiAlexa/Program.cs) of my program and, as you can see, there is no malicious code in it.
The false positive is probably caused by the the program's attempt to copy itself into Windows startup folder.
Please, if you can, report the case of false positive to Windows Defender to prevent other users from running into the same problem, thank you!

**Comment by LucaBarile** [comment]
I reported the false positive of Windows Defender to [Microsoft Security Intelligence](https://www.microsoft.com/en-us/wdsi/filesubmission) and they answered me in the following way:

> At this time, the submitted files do not meet our criteria for malware or potentially unwanted applications. The detection has been removed. Please follow the steps below to clear cached detections and obtain the latest malware definitions.

     1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender 
     2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
     3. Run "MpCmdRun.exe -SignatureUpdate"

> Alternatively, the latest definition is available for download here: https://docs.microsoft.com/microsoft-365/security/defender-endpoint/manage-updates-baselines-microsoft-defender-antivirus

Since the detection has been removed you shouldn’t have any more problems 👍
